export const projectCategories = [
  {
    name: 'Backdrops',
    images: [
      { src: '/images/projects/Backdrops/backdrop1.webp', width: 4000, height: 1868 },
      { src: '/images/projects/Backdrops/backdrop2.webp', width: 4000, height: 1848 },
      { src: '/images/projects/Backdrops/backdrop3.webp', width: 4000, height: 1848 },
      { src: '/images/projects/Backdrops/backdrop4.webp', width: 4000, height: 1848 },
      { src: '/images/projects/Backdrops/backdrop5.webp', width: 4000, height: 1848 },
      { src: '/images/projects/Backdrops/backdrop6.webp', width: 4000, height: 1848 },
      { src: '/images/projects/Backdrops/backdrop7.webp', width: 4000, height: 1848 },
      { src: '/images/projects/Backdrops/backdrop8.webp', width: 4000, height: 1848 },
      { src: '/images/projects/Backdrops/backdrop9.webp', width: 4000, height: 1848 },
      { src: '/images/projects/Backdrops/backdrop10.webp', width: 4000, height: 1848 },
      { src: '/images/projects/Backdrops/backdrop11.webp', width: 4000, height: 1848 },
      { src: '/images/projects/Backdrops/backdrop12.webp', width: 4000, height: 1848 },
      { src: '/images/projects/Backdrops/backdrop13.webp', width: 4000, height: 1848 },
      { src: '/images/projects/Backdrops/backdrop14.webp', width: 4000, height: 1848 },
    ],
  },
  {
    name: 'Centerpiece',
    images: [
      { src: '/images/projects/Centerpiece/centerpiece1.webp', width: 1848, height: 4000 },
      { src: '/images/projects/Centerpiece/centerpiece2.webp', width: 1848, height: 4000 },
      { src: '/images/projects/Centerpiece/centerpiece3.webp', width: 1848, height: 4000 },
      { src: '/images/projects/Centerpiece/centerpiece4.webp', width: 1848, height: 4000 },
      { src: '/images/projects/Centerpiece/centerpiece5.webp', width: 1848, height: 4000 },
      { src: '/images/projects/Centerpiece/centerpiece6.webp', width: 1848, height: 4000 },
      { src: '/images/projects/Centerpiece/centerpiece7.webp', width: 1848, height: 4000 },
      { src: '/images/projects/Centerpiece/centerpiece8.webp', width: 496, height: 767 },
      { src: '/images/projects/Centerpiece/centerpiece9.webp', width: 582, height: 1071 },
      { src: '/images/projects/Centerpiece/centerpiece10.webp', width: 539, height: 756 },
    ],
  },
  {
    name: 'Tables',
    images: [
      { src: '/images/projects/Tables/table1.webp', width: 1848, height: 4000 },
      { src: '/images/projects/Tables/table2.webp', width: 1848, height: 4000 },
      { src: '/images/projects/Tables/table3.webp', width: 1848, height: 4000 },
      { src: '/images/projects/Tables/table4.webp', width: 1848, height: 4000 },
      { src: '/images/projects/Tables/table5.webp', width: 4000, height: 1848 },
      { src: '/images/projects/Tables/table6.webp', width: 1848, height: 4000 },
      { src: '/images/projects/Tables/table7.webp', width: 600, height: 1175 },
      { src: '/images/projects/Tables/table8.webp', width: 4000, height: 1848 },
      { src: '/images/projects/Tables/table9.webp', width: 4000, height: 1848 },
    ],
  },
  {
    name: 'Ceiling Draping',
    images: [
      { src: '/images/projects/ceiling driping/ceiling-driping1.webp', width: 4000, height: 1868 },
      { src: '/images/projects/ceiling driping/ceiling-driping2.webp', width: 1868, height: 4000 },
      { src: '/images/projects/ceiling driping/ceiling-driping3.webp', width: 4000, height: 3000 },
      { src: '/images/projects/ceiling driping/ceiling-driping4.webp', width: 4000, height: 1848 },
      { src: '/images/projects/ceiling driping/ceiling-driping5.webp', width: 1848, height: 4000 },
      { src: '/images/projects/ceiling driping/ceiling-driping6.webp', width: 1848, height: 4000 },
      { src: '/images/projects/ceiling driping/ceiling-driping7.webp', width: 569, height: 1105 },
      { src: '/images/projects/ceiling driping/ceiling-driping8.webp', width: 4000, height: 1848 },
      { src: '/images/projects/ceiling driping/ceiling-driping9.webp', width: 4000, height: 1848 },
    ],
  },
  {
    name: 'Entrance',
    images: [
      { src: '/images/projects/entrance/entrance1.webp', width: 1868, height: 4000 },
      { src: '/images/projects/entrance/entrance2.webp', width: 1868, height: 4000 },
      { src: '/images/projects/entrance/entrance3.webp', width: 1868, height: 4000 },
      { src: '/images/projects/entrance/entrance4.webp', width: 1868, height: 4000 },
      { src: '/images/projects/entrance/entrance5.webp', width: 4000, height: 1868 },
      { src: '/images/projects/entrance/entrance6.webp', width: 1848, height: 4000 },
      { src: '/images/projects/entrance/entrance7.webp', width: 4000, height: 1848 },
      { src: '/images/projects/entrance/entrance8.webp', width: 4000, height: 1848 },
      { src: '/images/projects/entrance/entrance9.webp', width: 614, height: 1180 },
    ],
  },
];
